blueprint:
  name: Chuva, Dia/Noite e Temperatura
  description: |
    1) Fecha sempre que chover e não reabre sozinha pela chuva.
    2) Abre de dia se a temperatura estiver acima do valor definido.
    3) Fecha à noite com base no sensor de luminosidade.
  domain: automation

  input:
    rain_sensor:
      name: Sensor de Chuva
      description: Binary_sensor que indica chuva (on chovendo, off seco)
      selector:
        entity:
          filter:
            - domain: binary_sensor

    cover_entity:
      name: Cobertura
      description: Cobertura motorizada
      selector:
        entity:
          filter:
            - domain: cover

    position_sensor:
      name: Sensor de Porta da Cobertura
      description: Binary_sensor que indica se a cobertura está aberta (on) ou fechada (off)
      selector:
        entity:
          filter:
            - domain: binary_sensor

    lux_sensor:
      name: Sensor de Luminosidade
      description: Sensor de lux usado para saber se é dia ou noite
      selector:
        entity:
          filter:
            - domain: sensor

    weather_entity:
      name: Entidade de Tempo
      description: Entidade weather usada para pegar a temperatura
      default: weather.home
      selector:
        entity:
          filter:
            - domain: weather

    day_lux_threshold:
      name: Limite de Lux para Considerar Dia
      description: Acima deste valor é dia; abaixo é noite
      default: 1000
      selector:
        number:
          min: 1
          max: 20000
          unit_of_measurement: lx
          step: 100

    min_day_temperature:
      name: Temperatura Mínima para Abrir de Dia
      description: Só abre de dia se temperatura da entidade weather for maior ou igual a este valor
      default: 22
      selector:
        number:
          min: -10
          max: 50
          unit_of_measurement: °C
          step: 1

variables:
  rain_sensor: !input rain_sensor
  cover_entity: !input cover_entity
  position_sensor: !input position_sensor
  lux_sensor: !input lux_sensor
  weather_entity: !input weather_entity
  day_lux_threshold: !input day_lux_threshold
  min_day_temperature: !input min_day_temperature

triggers:
  # 1) Começou a chover -> sempre fecha
  - id: chuva_começou
    platform: state
    entity_id: !input rain_sensor
    to: "on"

  # 2) Mudança de luminosidade -> pode abrir/fechar pelo dia/noite
  - id: mudou_lux
    platform: state
    entity_id: !input lux_sensor

  # 3) Mudança de temperatura -> pode abrir de dia se estiver quente
  - id: mudou_temp
    platform: state
    entity_id: !input weather_entity

  # 4) Mudança manual de posição (porta) – para corrigir estado se usuário mexer
  - id: mudou_posicao
    platform: state
    entity_id: !input position_sensor

conditions: []

actions:
  - choose:
      # ======================================================
      # REGRA 1 – CHUVA: FECHAR E NÃO REABRIR PELA CHUVA
      # ======================================================
      - conditions:
          - condition: trigger
            id: chuva_começou
        sequence:
          # Se já estiver fechada pelo sensor de porta, não faz nada
          - condition: state
            entity_id: !input position_sensor
            state: "on"   # só fecha se o sensor diz que está aberta

          - service: cover.close_cover
            target:
              entity_id: !input cover_entity

      # ======================================================
      # REGRA 2 – DIA + TEMPERATURA: ABRIR
      # ======================================================
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: mudou_lux
              - condition: trigger
                id: mudou_temp
        sequence:
          # Nunca abrir se estiver chovendo
          - condition: state
            entity_id: !input rain_sensor
            state: "off"

          # Verifica se é dia pelo lux
          - condition: numeric_state
            entity_id: !input lux_sensor
            above: !input day_lux_threshold

          # Verifica temperatura da entidade weather
          - condition: template
            value_template: >
              {% set temp = state_attr(weather_entity, 'temperature') %}
              {{ temp is number and temp >= min_day_temperature }}

          # Só abre se estiver fechada pelo sensor de porta
          - condition: state
            entity_id: !input position_sensor
            state: "off"

          - service: cover.open_cover
            target:
              entity_id: !input cover_entity

      # ======================================================
      # REGRA 3 – NOITE: FECHAR
      # ======================================================
      - conditions:
          - condition: trigger
            id: mudou_lux
        sequence:
          # Se lux caiu abaixo do limite, consideramos noite
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: !input day_lux_threshold

          # Só fecha se estiver aberta pelo sensor de porta
          - condition: state
            entity_id: !input position_sensor
            state: "on"

          - service: cover.close_cover
            target:
              entity_id: !input cover_entity

mode: restart
