blueprint:
  name: Sensor Chuva, Lux, Previsão
  description: |
    Fecha cobertura automaticamente quando detectar chuva.
    Reabre apenas se não estiver chovendo, com base em luminosidade e/ou temperatura da previsão.
    Suporta sensor de posição e notificações.
  domain: automation

  input:
    rain_sensor:
      name: Sensor de Chuva
      description: Sensor que detecta quando está chovendo
      selector:
        entity:
          filter:
            - domain: binary_sensor

    cover_entity:
      name: Cobertura
      description: Cobertura a ser controlada
      selector:
        entity:
          filter:
            - domain: cover

    weather_entity:
      name: Entidade de Previsão do Tempo
      description: Entidade weather.* usada para checar condição e temperatura prevista
      default: weather.home
      selector:
        entity:
          filter:
            - domain: weather

    auto_reopen_section:
      name: Reabertura Automática
      icon: mdi:weather-sunny
      description: Configurações para reabrir automaticamente após a chuva
      collapsed: true
      input:
        enable_auto_reopen:
          name: Habilitar Reabertura Automática
          description: Reabrir cobertura automaticamente após chuva parar
          default: false
          selector:
            boolean:

        lux_sensor:
          name: Sensor de Luminosidade (Opcional)
          description: Só reabre se luminosidade estiver acima do valor definido
          default: {}
          selector:
            entity:
              filter:
                - domain: sensor
                  device_class: illuminance

        min_lux:
          name: Luminosidade Mínima para Reabrir
          description: Valor mínimo de lux necessário para reabrir (0 desativa verificação de lux)
          default: 0
          selector:
            number:
              min: 0
              max: 50000
              unit_of_measurement: lux
              step: 100

        min_forecast_temp:
          name: Temperatura Mínima da Previsão para Abrir
          description: Só abre se a temperatura da entidade weather for maior ou igual a este valor
          default: 22
          selector:
            number:
              min: -10
              max: 50
              unit_of_measurement: °C
              step: 1

    position_section:
      name: Sensor de Posição
      icon: mdi:arrow-expand-vertical
      description: Sensor adicional para verificar estado real da cobertura
      collapsed: true
      input:
        position_sensor:
          name: Sensor de Posição (Opcional)
          description: Sensor binário que indica se cobertura está aberta (on) ou fechada (off)
          default: {}
          selector:
            entity:
              filter:
                - domain: binary_sensor

    advanced_section:
      name: Configurações Avançadas
      icon: mdi:cog
      description: Opções extras de comportamento
      collapsed: true
      input:
        rain_confirmation_delay:
          name: Tempo de Confirmação de Chuva
          description: Segundos para confirmar chuva antes de fechar
          default: 3
          selector:
            number:
              min: 0
              max: 30
              unit_of_measurement: seconds
              step: 1

        send_notification:
          name: Enviar Notificações
          description: Notificar quando cobertura for fechada ou aberta
          default: false
          selector:
            boolean:

        notification_service:
          name: Serviço de Notificação
          description: Digite o serviço de notificação, como notify.notify ou notify.mobile_app_celular
          default: "notify.notify"
          selector:
            text:

variables:
  enable_auto_reopen: !input enable_auto_reopen
  lux_sensor: !input lux_sensor
  min_lux: !input min_lux
  position_sensor: !input position_sensor
  send_notification: !input send_notification
  notification_service: !input notification_service
  cover_entity: !input cover_entity
  weather_entity: !input weather_entity
  min_forecast_temp: !input min_forecast_temp

triggers:
  - platform: state
    id: rain_detected
    entity_id: !input rain_sensor
    to: "on"

  - platform: state
    id: rain_stopped
    entity_id: !input rain_sensor
    to: "off"

conditions: []

actions:
  - choose:
      # ======== CENÁRIO 1: CHUVA DETECTADA - FECHAR ========
      - conditions:
          - condition: trigger
            id: rain_detected
        sequence:
          # Aguarda confirmação (evita falsos positivos)
          - delay:
              seconds: !input rain_confirmation_delay

          # Verifica se ainda está chovendo após delay
          - condition: state
            entity_id: !input rain_sensor
            state: "on"

          # Verifica se cobertura está aberta (usando sensor de posição se disponível)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ position_sensor != {} }}"
                  - condition: state
                    entity_id: !input position_sensor
                    state: "on"   # on = aberta
                sequence: []
            default:
              - condition: template
                value_template: >
                  {{ is_state(cover_entity, 'open') or
                     is_state(cover_entity, 'opening') }}

          # Fecha a cobertura
          - service: cover.close_cover
            target:
              entity_id: !input cover_entity

          # Notificação (se habilitada)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ send_notification }}"
                sequence:
                  - service: "{{ notification_service }}"
                    data:
                      title: "Cobertura Fechada por Chuva"
                      message: "Chuva detectada. Cobertura fechada automaticamente às {{ now().strftime('%H:%M') }}."

      # ======== CENÁRIO 2: CHUVA PAROU - REABRIR (SE HABILITADO) ========
      - conditions:
          - condition: trigger
            id: rain_stopped
          - condition: template
            value_template: "{{ enable_auto_reopen }}"
        sequence:
          # Garante que o sensor de chuva físico está seco
          - condition: state
            entity_id: !input rain_sensor
            state: "off"

          # Garante que condição atual do weather não é de chuva
          - condition: template
            value_template: >
              {% set cond = state_attr(weather_entity, 'condition') %}
              {{ cond not in ['rain', 'pouring', 'lightning', 'lightning-rainy', 'snow', 'hail'] }}

          # Verifica temperatura prevista da entidade weather.*
          - condition: template
            value_template: >
              {% set temp = state_attr(weather_entity, 'temperature') %}
              {{ temp is number and temp >= min_forecast_temp }}

          # Verifica luminosidade (se configurada e min_lux > 0)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ lux_sensor != {} and min_lux > 0 }}"
                sequence:
                  - condition: numeric_state
                    entity_id: !input lux_sensor
                    above: !input min_lux

          # Verifica se cobertura está fechada (usando sensor de posição se disponível)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ position_sensor != {} }}"
                  - condition: state
                    entity_id: !input position_sensor
                    state: "off"   # off = fechada
                sequence: []
            default:
              - condition: template
                value_template: >
                  {{ is_state(cover_entity, 'closed') or
                     is_state(cover_entity, 'closing') }}

          # Abre a cobertura
          - service: cover.open_cover
            target:
              entity_id: !input cover_entity

          # Notificação (se habilitada)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ send_notification }}"
                sequence:
                  - service: "{{ notification_service }}"
                    data:
                      title: "Cobertura Aberta após Chuva"
                      message: >
                        Cobertura reaberta automaticamente às {{ now().strftime('%H:%M') }}.
                        {% set temp = state_attr(weather_entity, 'temperature') %}
                        {% if temp is number %}
                        Temperatura previsão: {{ temp }} °C.
                        {% endif %}
                        {% if lux_sensor != {} %}
                        Luminosidade: {{ states(lux_sensor) }} lux.
                        {% endif %}

mode: restart
