blueprint:
  name: Luz com Horário
  description: >
    Liga luz por horário, presença e luminosidade.
    - Liga no horário principal se luminosidade estiver abaixo do limite (opcional)
    - Desliga no horário final
    - Fora do horário principal: liga somente por presença
    - Após pôr do sol: presença NÃO liga mais
    - Desliga por ausência depois do tempo configurado.
  domain: automation

  input:

    luzes:
      name: Luz(s) / Switch(s)
      selector:
        target:
          entity:
            domain: [light, switch]

    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor

    sensor_lux:
      name: Sensor de luminosidade (opcional)
      default: ""
      selector:
        entity:
          domain: sensor

    limite_lux:
      name: Limiar de luminosidade para ligar (opcional)
      description: Se vazio, a luminosidade não será usada.
      default: 20
      selector:
        number:
          min: 0
          max: 5000
          mode: box

    usar_lux_no_horario:
      name: Usar luminosidade no horário principal?
      default: false
      selector:
        boolean:

    tempo_ausencia:
      name: Tempo sem presença para desligar
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
      default: 180

    horario_inicio:
      name: Horário inicial
      default: "18:00:00"
      selector:
        time:

    horario_fim:
      name: Horário final
      default: "00:00:00"
      selector:
        time:

trigger:

  # Presença detectada
  - platform: state
    entity_id: !input sensor_presenca
    to: "on"

  # Ausência por tempo configurado
  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for:
      seconds: !input tempo_ausencia

  # Horário de ligar
  - platform: time
    at: !input horario_inicio

  # Horário de desligar
  - platform: time
    at: !input horario_fim

variables:
  usar_lux: !input usar_lux_no_horario
  lux_sensor: !input sensor_lux
  lux_limite: !input limite_lux

action:
  - choose:

      ###################################################################
      # 1 — HORÁRIO PRINCIPAL (liga no horário, com lux opcional)
      ###################################################################
      - conditions:
          - condition: time
            at: !input horario_inicio
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ not usar_lux or
                         (states(lux_sensor) | float(9999) < lux_limite) }}
                sequence:
                  - service: homeassistant.turn_on
                    target: !input luzes

      ###################################################################
      # 2 — HORÁRIO FINAL (sempre desliga)
      ###################################################################
      - conditions:
          - condition: time
            at: !input horario_fim
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes

      ###################################################################
      # 3 — PRESENÇA FORA DO HORÁRIO PRINCIPAL
      ###################################################################
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "on"
          - condition: template
            value_template: >
              {% set inicio = states('input_datetime.horario_inicio') %}
              {% set fim = states('input_datetime.horario_fim') %}
              {{ not (inicio <= now().strftime('%H:%M:%S') <= fim) }}
          - condition: sun
            after: sunrise
            before: sunset
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      ###################################################################
      # 4 — DESLIGAMENTO POR AUSÊNCIA (somente se luz estiver ligada)
      ###################################################################
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "off"
          - condition: state
            entity_id: !input luzes
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
