blueprint:
  name: Liga e Desliga Luz por Horario
  description: >
    Funciona agora apenas com horário.
    Se você adicionar um sensor de presença no futuro, ele ativará a lógica de movimento automaticamente.
  domain: automation

  input:
    luzes:
      name: Luz(es) ou Switch(es)
      selector:
        target:
          entity:
            domain: [light, switch]

    horario_inicio:
      name: Horário para LIGAR
      default: "18:00:00"
      selector:
        time:

    horario_fim:
      name: Horário para DESLIGAR
      default: "00:00:00"
      selector:
        time:

    # Sensor agora é opcional e tem um default vazio seguro
    sensor_presenca:
      name: Sensor de presença (Futuro)
      description: Deixe vazio por enquanto. Quando tiver o sensor, selecione-o aqui.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true  # Truque para aceitar lista vazia

    tempo_ausencia:
      name: Tempo para desligar (quando tiver sensor)
      default: 180
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: seconds

    sensor_lux:
      name: Sensor de Lux (Opcional)
      default: []
      selector:
        entity:
          domain: sensor
          multiple: true

    limite_lux:
      name: Limite Lux
      default: 20
      selector:
        number:
          min: 0
          max: 5000

trigger:
  # 1. Horários (Sempre funcionam)
  - platform: time
    at: !input horario_inicio
    id: "time_on"

  - platform: time
    at: !input horario_fim
    id: "time_off"

  # 2. Presença (Template Trigger seguro)
  # Só dispara se houver sensor definido E ele mudar para ON
  - platform: template
    id: "motion_on"
    value_template: >
      {% set sensors = inputs.sensor_presenca %}
      {% if sensors is defined and sensors|length > 0 %}
        {{ is_state(sensors[0], 'on') }}
      {% else %}
        false
      {% endif %}

  # 3. Ausência (Template Trigger seguro)
  # Só dispara se houver sensor definido E ele ficar OFF pelo tempo
  - platform: template
    id: "motion_off"
    value_template: >
      {% set sensors = inputs.sensor_presenca %}
      {% if sensors is defined and sensors|length > 0 %}
        {{ is_state(sensors[0], 'off') }}
      {% else %}
        false
      {% endif %}
    for: !input tempo_ausencia

action:
  - choose:
      # CENA 1: LIGAR NO HORÁRIO
      - conditions:
          - condition: trigger
            id: "time_on"
          - condition: template
            value_template: >
              {% set lux_sensors = inputs.sensor_lux %}
              {% set limit = inputs.limite_lux %}
              {% if lux_sensors is defined and lux_sensors|length > 0 %}
                 {{ states(lux_sensors[0])|float(9999) < limit }}
              {% else %}
                 true
              {% endif %}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # CENA 2: DESLIGAR NO HORÁRIO
      - conditions:
          - condition: trigger
            id: "time_off"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes

      # CENA 3: MOVIMENTO (LIGAR)
      - conditions:
          - condition: trigger
            id: "motion_on"
          - condition: template
            value_template: >
              {{ is_state('sun.sun', 'above_horizon') and
                 not (inputs.horario_inicio <= now().strftime('%H:%M:%S') <= inputs.horario_fim) }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # CENA 4: AUSÊNCIA (DESLIGAR)
      - conditions:
          - condition: trigger
            id: "motion_off"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
