blueprint:
  name: Luz com Horário
  description: >
    Automação completa com horário, presença opcional e luminosidade opcional.
    - Liga no horário inicial (com ou sem lux)
    - Desliga no horário final
    - Fora do horário liga por presença (se existir sensor)
    - Após pôr do sol, presença não liga mais
    - Desliga por ausência (se existir sensor)
  domain: automation

  input:

    luzes:
      name: Luz(es) ou Switch(es)
      selector:
        target:
          entity:
            domain: [light, switch]

    sensor_presenca:
      name: Sensor de presença (opcional)
      default: ""
      selector:
        entity:
          domain: binary_sensor

    sensor_lux:
      name: Sensor de luminosidade (opcional)
      default: ""
      selector:
        entity:
          domain: sensor

    limite_lux:
      name: Limiar de luminosidade para ligar (opcional)
      default: 20
      selector:
        number:
          min: 0
          max: 5000
          mode: box

    usar_lux_no_horario:
      name: Usar luminosidade no horário principal?
      default: false
      selector:
        boolean:

    tempo_ausencia:
      name: Tempo sem presença para desligar (se houver sensor)
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
      default: 180

    horario_inicio:
      name: Horário para ligar
      default: "18:00:00"
      selector:
        time:

    horario_fim:
      name: Horário para desligar
      default: "00:00:00"
      selector:
        time:

trigger:

  - platform: state
    entity_id: !input sensor_presenca
    to: "on"

  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for:
      seconds: !input tempo_ausencia

  - platform: time
    at: !input horario_inicio

  - platform: time
    at: !input horario_fim

variables:
  sensor_presenca: !input sensor_presenca
  sensor_lux: !input sensor_lux
  usar_lux: !input usar_lux_no_horario
  limite_lux: !input limite_lux
  luzes: !input luzes

action:
  - choose:

      # 1 — LIGAR NO HORÁRIO (com luminosidade opcional)
      - conditions:
          - condition: template
            value_template: >
              {{ not usar_lux or
                 (sensor_lux != "" and (states(sensor_lux) | float(9999) < limite_lux)) }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # 2 — DESLIGAR NO HORÁRIO FINAL
      - conditions:
          - condition: template
            value_template: "true"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes

      # 3 — LIGAR POR PRESENÇA FORA DO HORÁRIO (somente se houver sensor)
      - conditions:
          - condition: template
            value_template: >
              {{ sensor_presenca != '' and
                 is_state(sensor_presenca, 'on') and
                 is_state('sun.sun', 'above_horizon') and
                 not (inputs.horario_inicio <= now().strftime('%H:%M:%S') <= inputs.horario_fim)
              }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # 4 — DESLIGAR POR AUSÊNCIA (somente se houver sensor)
      - conditions:
          - condition: template
            value_template: >
              {{ sensor_presenca != '' and
                 is_state(sensor_presenca, 'off') and
                 (expand(luzes) | selectattr('state', 'eq', 'on') | list | count > 0)
              }}
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
