blueprint:
  name: Liga e Desliga Luz por Horario
  description: >
    - 18h às 00h: Liga direto.
    - 00h: Desliga.
    - 00h até Amanhecer: Liga só com movimento.
    - Dia: Não liga.
  domain: automation

  input:
    luzes:
      name: Luz(es)
      selector:
        target:
          entity:
            domain: [light, switch]

    horario_inicio:
      name: Horário LIGAR fixo
      default: "18:00:00"
      selector:
        time:

    horario_fim:
      name: Horário DESLIGAR fixo (Início da Madrugada)
      default: "00:00:00"
      selector:
        time:

    sensor_presenca:
      name: Sensor de Presença (Futuro)
      description: Deixe vazio se não tiver.
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    tempo_ausencia:
      name: Tempo para desligar na madrugada
      default: 180
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: seconds

    sensor_lux:
      name: Sensor de Lux (Opcional)
      default: []
      selector:
        entity:
          domain: sensor
          multiple: true

    limite_lux:
      name: Limite de Lux (Escuro o bastante?)
      default: 20
      selector:
        number:
          min: 0
          max: 5000

trigger:
  # 1. Horários
  - platform: time
    at: !input horario_inicio
    id: "time_on"

  - platform: time
    at: !input horario_fim
    id: "time_off"

  # 2. Movimento (Seguro se vazio)
  - platform: template
    id: "motion_on"
    value_template: >
      {% set s = inputs.sensor_presenca %}
      {{ s is defined and s|length > 0 and is_state(s[0], 'on') }}

  # 3. Ausência (Seguro se vazio)
  - platform: template
    id: "motion_off"
    value_template: >
      {% set s = inputs.sensor_presenca %}
      {{ s is defined and s|length > 0 and is_state(s[0], 'off') }}
    for: !input tempo_ausencia

action:
  - choose:
      # CENA 1: LIGAR FIXO (INÍCIO DA NOITE)
      # Verifica Lux se disponível, senão liga direto
      - conditions:
          - condition: trigger
            id: "time_on"
          - condition: template
            value_template: >
              {% set l = inputs.sensor_lux %}
              {% if l is defined and l|length > 0 %}
                {{ states(l[0])|float(9999) < inputs.limite_lux }}
              {% else %}
                true
              {% endif %}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # CENA 2: DESLIGAR FIXO (MEIA-NOITE)
      - conditions:
          - condition: trigger
            id: "time_off"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes

      # CENA 3: MOVIMENTO NA MADRUGADA (LIGAR)
      # Regra: Sol ABAIXO do horizonte (noite) E fora do horário fixo
      - conditions:
          - condition: trigger
            id: "motion_on"
          - condition: template
            value_template: >
              {{ is_state('sun.sun', 'below_horizon') }}
          - condition: template
            value_template: >
              {% set inicio = inputs.horario_inicio %}
              {% set fim = inputs.horario_fim %}
              {% set agora = now().strftime('%H:%M:%S') %}
              {# Só liga se NÃO estiver no período fixo (já estaria ligada) #}
              {{ not (inicio <= agora or agora <= fim) if inicio > fim else not (inicio <= agora <= fim) }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # CENA 4: AUSÊNCIA (DESLIGAR)
      - conditions:
          - condition: trigger
            id: "motion_off"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
