blueprint:
  name: Luz com Horário e Presença
  description: >
    Automação híbrida:
    1. Liga/Desliga em horários fixos.
    2. Liga por presença se estiver fora do horário e sol acima do horizonte.
    3. Desliga por ausência após X segundos.
  domain: automation

  input:
    luzes:
      name: Luz(es) ou Switch(es)
      selector:
        target:
          entity:
            domain: [light, switch]

    sensor_presenca:
      name: Sensor de presença (Obrigatório)
      description: Selecione o sensor que detecta movimento.
      selector:
        entity:
          domain: binary_sensor

    usar_sensor_presenca:
      name: Ativar regra de presença?
      description: Se desligado, só obedece aos horários fixos.
      default: true
      selector:
        boolean:

    sensor_lux:
      name: Sensor de luminosidade (Opcional)
      default: ""
      selector:
        entity:
          domain: sensor

    usar_sensor_lux:
      name: Usar sensor de luminosidade no horário fixo?
      default: false
      selector:
        boolean:

    limite_lux:
      name: Limiar de luminosidade
      default: 20
      selector:
        number:
          min: 0
          max: 5000
          mode: box

    tempo_ausencia:
      name: Tempo sem presença para desligar
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: seconds
      default: 180

    horario_inicio:
      name: Horário fixo para LIGAR
      default: "18:00:00"
      selector:
        time:

    horario_fim:
      name: Horário fixo para DESLIGAR
      default: "00:00:00"
      selector:
        time:

trigger:
  # 1. Horários Fixos
  - platform: time
    at: !input horario_inicio
    id: "time_on"

  - platform: time
    at: !input horario_fim
    id: "time_off"

  # 2. Sensor de Presença (Ligar)
  - platform: state
    entity_id: !input sensor_presenca
    to: "on"
    id: "motion_on"

  # 3. Sensor de Presença (Desligar após tempo)
  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for: !input tempo_ausencia
    id: "motion_off"

variables:
  usar_presenca: !input usar_sensor_presenca
  usar_lux: !input usar_sensor_lux
  sensor_lux: !input sensor_lux
  limite_lux: !input limite_lux

action:
  - choose:
      # ---------------------------------------------------------
      # 1: Horário de Ligar (verifica Lux se ativado)
      # ---------------------------------------------------------
      - conditions:
          - condition: trigger
            id: "time_on"
          - condition: template
            value_template: >
              {{ not usar_lux or 
                 (sensor_lux != "" and states(sensor_lux)|float(9999) < limite_lux) }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # ---------------------------------------------------------
      # 2: Horário de Desligar (Fixo)
      # ---------------------------------------------------------
      - conditions:
          - condition: trigger
            id: "time_off"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes

      # ---------------------------------------------------------
      # 3: Movimento (Ligar)
      #    Regra: Presença Ativa + Sol visível + FORA do horário noturno
      # ---------------------------------------------------------
      - conditions:
          - condition: trigger
            id: "motion_on"
          - condition: template
            value_template: "{{ usar_presenca }}"
          - condition: template
            value_template: >
              {{ is_state('sun.sun', 'above_horizon') and
                 not (inputs.horario_inicio <= now().strftime('%H:%M:%S') <= inputs.horario_fim) }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # ---------------------------------------------------------
      # 4: Ausência (Desligar)
      #    Regra: Presença Ativa + Sensor ficou OFF pelo tempo configurado
      # ---------------------------------------------------------
      - conditions:
          - condition: trigger
            id: "motion_off"
          - condition: template
            value_template: "{{ usar_presenca }}"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
