blueprint:
  name: Luz com Horário
  description: >
    Automação completa com horário, presença opcional e luminosidade opcional.
    - Liga no horário inicial (com ou sem lux)
    - Desliga no horário final
    - Fora do horário liga por presença (se habilitado e sensor existir)
    - Após pôr do sol, presença não liga mais
    - Desliga por ausência (se habilitado e sensor existir)
  domain: automation

  input:

    luzes:
      name: Luz(es) ou Switch(es)
      selector:
        target:
          entity:
            domain: [light, switch]

    sensor_presenca:
      name: Sensor de presença
      default: ""
      selector:
        entity:
          domain: binary_sensor

    usar_sensor_presenca:
      name: Usar sensor de presença?
      default: false
      selector:
        boolean:

    sensor_lux:
      name: Sensor de luminosidade
      default: ""
      selector:
        entity:
          domain: sensor

    usar_sensor_lux:
      name: Usar sensor de luminosidade?
      default: false
      selector:
        boolean:

    limite_lux:
      name: Limiar de luminosidade para ligar
      default: 20
      selector:
        number:
          min: 0
          max: 5000
          mode: box

    tempo_ausencia:
      name: Tempo sem presença para desligar (se usar sensor de presença)
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
      default: 180

    horario_inicio:
      name: Horário para ligar
      default: "18:00:00"
      selector:
        time:

    horario_fim:
      name: Horário para desligar
      default: "00:00:00"
      selector:
        time:

trigger:
  # Triggers apenas no horário para evitar erro se sensor for vazio
  - platform: time
    at: !input horario_inicio

  - platform: time
    at: !input horario_fim

variables:
  sensor_presenca: !input sensor_presenca
  usar_sensor_presenca: !input usar_sensor_presenca
  sensor_lux: !input sensor_lux
  usar_sensor_lux: !input usar_sensor_lux
  limite_lux: !input limite_lux
  luzes: !input luzes
  tempo_ausencia: !input tempo_ausencia

action:
  - choose:

      # 1 — LIGAR NO HORÁRIO (com luminosidade opcional e flag)
      - conditions:
          - condition: template
            value_template: >
              {{ not usar_sensor_lux or
                 (sensor_lux != "" and (states(sensor_lux) | float(9999) < limite_lux)) }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # 2 — DESLIGAR NO HORÁRIO FINAL
      - conditions:
          - condition: template
            value_template: "true"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes

      # 3 — LIGAR POR PRESENÇA FORA DO HORÁRIO (se habilitado e sensor existir)
      - conditions:
          - condition: template
            value_template: >
              {{ usar_sensor_presenca and
                 sensor_presenca != "" and
                 is_state(sensor_presenca, 'on') and
                 is_state('sun.sun', 'above_horizon') and
                 not (inputs.horario_inicio <= now().strftime('%H:%M:%S') <= inputs.horario_fim)
              }}
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # 4 — DESLIGAR POR AUSÊNCIA (se habilitado e sensor existir)
      - conditions:
          - condition: template
            value_template: >
              {{ usar_sensor_presenca and
                 sensor_presenca != "" and
                 is_state(sensor_presenca, 'off') and
                 (expand(luzes) | selectattr('state', 'eq', 'on') | list | count > 0)
              }}
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
