blueprint:
  name: Liga/Desliga Luz por Horario Determinado
  description: Apenas liga e desliga as luzes nos horários programados.
  domain: automation

  input:
    luzes:
      name: Luz(es) para controlar
      selector:
        target:
          entity:
            domain: [light, switch]

    horario_ligar:
      name: Horário para LIGAR
      default: "18:00:00"
      selector:
        time:

    horario_desligar:
      name: Horário para DESLIGAR
      default: "00:00:00"
      selector:
        time:

trigger:
  - platform: time
    at: !input horario_ligar
    id: "ligar"

  - platform: time
    at: !input horario_desligar
    id: "desligar"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ligar"
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      - conditions:
          - condition: trigger
            id: "desligar"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
