blueprint:
  name: Paralelo Virtual V3
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

mode: restart

trigger:
  - platform: state
    entity_id: !input entrada_switchs

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state in ['on', 'off'] }}"

action:
  - service: "homeassistant.turn_{{ trigger.to_state.state }}"
    target:
      entity_id: !input entrada_switchs
