blueprint:
  name: Desliga Luzes após Ausência
  description: Desliga uma ou mais luzes/switches quando o sensor de presença fica OFF por um tempo.
  domain: automation

  input:
    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor

    luzes:
      name: Luzes/Switches que serão desligados
      selector:
        entity:
          multiple: true
          domain:
            - light
            - switch

    tempo_ausencia:
      name: Tempo sem presença para desligar (segundos)
      default: 60
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: seconds

mode: restart

trigger:
  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for: !input tempo_ausencia

condition: []

action:
  - service: homeassistant.turn_off
    target:
      entity_id: !input luzes
