blueprint:
  name: Desliga Luzes por Presença e Dias
  description: Desliga uma ou mais luzes quando não há presença, somente nos dias escolhidos da semana.
  domain: automation

  input:
    motion_sensor:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor

    target_lights:
      name: Luzes a controlar
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    no_motion_wait:
      name: Tempo sem presença para desligar (segundos)
      default: 300
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: seconds
          mode: slider

    active_days:
      name: Dias da semana em que DESLIGA
      description: Nesses dias a automação poderá desligar as luzes.
      selector:
        select:
          multiple: true
          mode: list
          options:
            - label: Segunda
              value: mon
            - label: Terça
              value: tue
            - label: Quarta
              value: wed
            - label: Quinta
              value: thu
            - label: Sexta
              value: fri
            - label: Sábado
              value: sat
            - label: Domingo
              value: sun
      default:
        - mon
        - tue
        - wed
        - thu
        - fri

mode: restart

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "off"
    for:
      seconds: !input no_motion_wait

condition:
  - condition: template
    value_template: >
      {% set days = !input active_days %}
      {{ now().strftime('%a')[:3] | lower in days }}

action:
  - service: light.turn_off
    target: !input target_lights
