blueprint:
  name: Desliga Luzes quando não há Presença
  description: Desliga uma ou mais luzes quando o sensor de presença fica em falso por um tempo.
  domain: automation

  input:
    motion_sensor:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor

    target_lights:
      name: Luzes / Interruptores a controlar
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    no_motion_wait:
      name: Tempo sem presença para desligar (segundos)
      default: 300
      selector:
        number:
          min: 5
          max: 3600
          unit_of_measurement: seconds
          mode: slider

mode: restart

# Dispara quando o sensor passa a NÃO detectar presença
trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "false"
    for:
      seconds: !input no_motion_wait

condition: []

action:
  - service: homeassistant.turn_off
    target: !input target_lights
