blueprint:
  name: Reset (Reconfigure) dispositivo Zigbee2MQTT
  description: Envia comando de reconfigure para um dispositivo Zigbee2MQTT.
  domain: automation

  input:
    trigger_button:
      name: Botão para acionar
      description: Entidade que dispara a automação
      selector:
        entity: {}

    z2m_device_name:
      name: Nome do dispositivo no Zigbee2MQTT
      description: Nome exatamente como aparece no Z2M
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input trigger_button

action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/request/device/reconfigure
      payload: "{{ {'id': z2m_device_name} | tojson }}"

mode: single
