blueprint:
  name: Resetar Dispositivo Zigbee2MQTT
  description: Envia comando de reset via MQTT.
  domain: automation
  input:
    target_device:
      name: Dispositivo
      description: Selecione o dispositivo a resetar.
      selector:
        device:
          integration: mqtt

# AQUI ESTAVA O ERRO. AGORA ESTÁ CORRIGIDO:
trigger:
  - platform: event
    event_type: gatilho_ficticio_apenas_para_salvar

variables:
  device_var: !input target_device
  device_name: "{{ device_attr(device_var, 'name') }}"

action:
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{ device_name }}/set"
      payload: '{"reset": true}'
