blueprint:
  name: Resetar Dispositivo Zigbee2MQTT
  description: Envia comando de reset para o dispositivo selecionado. O nome no HA deve ser igual ao do Z2M.
  domain: automation
  input:
    target_device:
      name: Dispositivo
      description: Selecione o dispositivo Zigbee que deseja resetar.
      selector:
        device:
          integration: mqtt

# Correção do erro: Trocamos 'manual' (que não existe) por 'event'
trigger:
  - platform: event
    event_type: acionar_reset_manual

variables:
  # Captura o ID do dispositivo selecionado
  device_var: !input target_device
  # Pega o nome do dispositivo. 
  # IMPORTANTE: Se o nome no HA for diferente do Zigbee2MQTT, o reset não vai funcionar.
  device_name: "{{ device_attr(device_var, 'name') }}"

action:
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{ device_name }}/set"
      payload: '{"reset": true}'
