blueprint:
  name: Reset (Reconfigure) dispositivo Zigbee2MQTT
  description: >
    Envia comando de reconfigure para um dispositivo Zigbee2MQTT,
    útil para corrigir falhas de comunicação sem remover o device.
  domain: automation

  input:
    trigger_button:
      name: Botão para acionar
      description: Input_button, input_boolean, switch, etc.
      selector:
        entity: {}

    z2m_device_name:
      name: Nome do dispositivo no Zigbee2MQTT
      description: Exatamente como aparece no Z2M (ex: "sala_lampada", "0x842e14fffec12a9b")
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input trigger_button

action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/request/device/reconfigure
      payload: >
        {"id":"{{ (z2m_device_name) }}"}

mode: single
