blueprint:
  name: Resetar Dispositivo Zigbee2MQTT (Manual)
  description: Envia comando de reset via MQTT para o dispositivo selecionado. O nome do dispositivo no HA deve corresponder ao friendly_name no Z2M.
  domain: automation
  input:
    target_device:
      name: Dispositivo
      description: Selecione o dispositivo Zigbee que deseja resetar.
      selector:
        device:
          integration: mqtt

trigger:
  - platform: manual

variables:
  # Captura o ID do dispositivo selecionado no input
  target_device_id: !input target_device
  # Tenta obter o nome do dispositivo para usar no tópico
  device_name: "{{ device_attr(target_device_id, 'name') }}"

action:
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{ device_name }}/set"
      payload: '{"reset": true}'
