blueprint:
  name: Resetar Dispositivo Zigbee2MQTT
  description: Envia comando de reset via MQTT para o dispositivo selecionado.
  domain: automation
  input:
    target_device:
      name: Dispositivo
      description: Selecione o dispositivo que deve ser resetado.
      selector:
        device:
          integration: mqtt

# Gatilho fictício apenas para validar a automação.
# A automação será executada quando você clicar em "Executar".
trigger:
  - platform: event
    event_type: disparar_reset_manual

variables:
  # Captura o ID do dispositivo escolhido
  device_var: !input target_device
  # Extrai o nome do dispositivo no Home Assistant.
  # IMPORTANTE: Este nome deve ser IDÊNTICO ao nome no Zigbee2MQTT.
  device_name: "{{ device_attr(device_var, 'name') }}"

action:
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{ device_name }}/set"
      payload: '{"reset": true}'
