blueprint:
  name: Resetar Dispositivo Zigbee (Automação)
  domain: automation
  input:
    target_device:
      name: Dispositivo
      selector:
        device:
          integration: mqtt

# Gatilho falso apenas para o HA parar de reclamar
trigger:
  - platform: template
    value_template: "{{ false }}"

variables:
  device_var: !input target_device
  device_name: "{{ device_attr(device_var, 'name') }}"

action:
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{ device_name }}/set"
      payload: '{"reset": true}'
