blueprint:
  name: Resetar Dispositivo Zigbee2MQTT
  description: Envia comando de reset via MQTT para o dispositivo selecionado. O nome no HA deve ser igual ao do Z2M.
  domain: automation
  input:
    target_device:
      name: Dispositivo
      description: Selecione o dispositivo Zigbee que deseja resetar.
      selector:
        device:
          integration: mqtt

trigger:
  - platform: manual

variables:
  # Cria uma variável com o dispositivo escolhido no input
  target_device_input: !input target_device
  # Extrai o nome "amigável" do dispositivo para usar no tópico
  device_name: "{{ device_attr(target_device_input, 'name') }}"

action:
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{ device_name }}/set"
      payload: '{"reset": true}'
