blueprint:
  name: Resetar Dispositivo Zigbee2MQTT
  description: Envia comando de reset para um dispositivo selecionado.
  domain: automation
  input:
    target_device:
      name: Dispositivo
      description: Selecione o dispositivo a ser resetado.
      selector:
        device:
          integration: mqtt

trigger:
  - platform: manual

variables:
  # Captura o dispositivo selecionado
  device_var: !input target_device
  # Pega o nome do dispositivo para usar no tópico MQTT
  # O nome no Home Assistant deve ser IGUAL ao nome no Zigbee2MQTT
  device_name: "{{ device_attr(device_var, 'name') }}"

action:
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{ device_name }}/set"
      payload: '{"reset": true}'
