blueprint:
  name: Sensor de Presença
  domain: automation
  input:
    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor
    luz:
      name: Luz/switch que será controlado
      selector:
        entity:
          domain:
            - light
            - switch
    tempo_ausencia:
      name: Tempo sem presença para desligar
      default: 180
      selector:
        number:
          min: 10
          max: 1800
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input sensor_presenca
    to: "on"
  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for: !input tempo_ausencia

action:
  - choose:

      # REGRA 1: Presença -> ligar a luz imediatamente
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "on"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input luz

      # REGRA 2: Ausência por X segundos -> desliga a luz SE a luz estiver ligada
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "off"
          - condition: state
            entity_id: !input luz
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input luz
