blueprint:
  name: Sensor de Presença com Bloqueio pelo Interruptor
  description: >
    Liga a luz ao detectar presença e desliga após tempo sem presença.
    Se a luz for desligada manualmente (estado OFF), o sensor não religa.
  domain: automation

  input:
    motion_sensor:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy

    target_light:
      name: Luz ou Interruptor
      selector:
        entity:
          domain:
            - light
            - switch

    timeout:
      name: Minutos sem presença para desligar
      default: 3
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: minutes

mode: restart
max_exceeded: silent

variables:
  motion_sensor: !input motion_sensor
  target: !input target_light
  timeout: !input timeout

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

  - platform: state
    entity_id: !input motion_sensor
    from: "on"
    to: "off"

action:
  - choose:
      # ===== PRESENÇA DETECTADA =====
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
          - condition: state
            entity_id: !input target_light
            state: "off"
        sequence:
          # Se for LIGHT
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ target.startswith('light.') }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input target_light

              # Se for SWITCH
              - conditions:
                  - condition: template
                    value_template: "{{ target.startswith('switch.') }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input target_light

      # ===== SEM PRESENÇA =====
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - delay:
              minutes: !input timeout
          - condition: state
            entity_id: !input motion_sensor
            state: "off"

          # Desligar LIGHT
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ target.startswith('light.') }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input target_light

              # Desligar SWITCH
              - conditions:
                  - condition: template
                    value_template: "{{ target.startswith('switch.') }}"
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input target_light
