blueprint:
  name: Sensor de Presença
  domain: automation
  input:
    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor

    luzes:
      name: Luzes/Switches que serão controlados
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    tempo_ausencia:
      name: Tempo sem presença para desligar
      default: 180
      selector:
        number:
          min: 10
          max: 1800
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input sensor_presenca
    to: "on"

  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for: !input tempo_ausencia

action:
  - choose:

      # REGRA 1 — Presença → LIGAR imediatamente
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "on"
        sequence:
          - service: homeassistant.turn_on
            target: !input luzes

      # REGRA 2 — Após X segundos sem presença → DESLIGAR se estiver ligada
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "off"
          - condition: state
            target: !input luzes
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target: !input luzes
