blueprint:
  name: Sensor de Presença com Bloqueio pelo Interruptor
  description: >
    Liga a luz ou switch quando detectar presença e desliga após X minutos sem presença.
    Se o usuário desligar manualmente, o sensor não religa.
  domain: automation

  input:
    motion_sensor:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy

    target_entity:
      name: Luz ou Interruptor
      selector:
        entity:
          domain:
            - light
            - switch

    timeout:
      name: Minutos sem presença
      default: 3
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

mode: restart

trigger:
  - platform: state
    entity_id: !input motion_sensor

variables:
  target: !input target_entity
  motion: !input motion_sensor
  timeout: !input timeout

action:
  - choose:
      # ======= SENSOR DETECTA PRESENÇA =======
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
          - condition: state
            entity_id: !input target_entity
            state: "off"
        sequence:
          - service: >
              homeassistant.turn_on
            target:
              entity_id: !input target_entity

      # ======= SENSOR FICA SEM PRESENÇA =======
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - delay:
              minutes: !input timeout
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
          - service: >
              homeassistant.turn_off
            target:
              entity_id: !input target_entity
