blueprint:
  name: Sensor de Presença com Luminosidade
  domain: automation

  input:

    sensor_presenca:
      name: Sensor de presença
      selector:
        entity:
          domain: binary_sensor

    sensor_luminosidade:
      name: Sensor de luminosidade (opcional)
      default: ""
      selector:
        entity:
          domain: sensor

    limite_lux:
      name: Não ligar se a luminosidade estiver acima de
      default: 30
      selector:
        number:
          min: 0
          max: 3000
          unit_of_measurement: lx

    luzes:
      name: Luzes/Switches que serão controladas
      selector:
        entity:
          multiple: true
          domain:
            - light
            - switch

    tempo_ausencia:
      name: Tempo sem presença para desligar
      default: 180
      selector:
        number:
          min: 10
          max: 1800
          unit_of_measurement: seconds


variables:
  lux_sensor: !input sensor_luminosidade
  lux_limit: !input limite_lux


trigger:
  - platform: state
    entity_id: !input sensor_presenca
    to: "on"

  - platform: state
    entity_id: !input sensor_presenca
    to: "off"
    for: !input tempo_ausencia


action:
  - choose:

      # ---------- REGRA 1 — PRESENÇA → LIGAR ----------
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "on"

          - condition: template
            value_template: >
              {% if lux_sensor in ['', None] %}
                true
              {% else %}
                {{ states(lux_sensor) | float(0) < lux_limit }}
              {% endif %}
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: !input luzes

      # ---------- REGRA 2 — AUSÊNCIA → DESLIGAR ----------
      - conditions:
          - condition: state
            entity_id: !input sensor_presenca
            state: "off"
          - condition: state
            entity_id: !input luzes
            state: "on"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: !input luzes
